# Generated by Django 4.2.7 on 2023-12-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'benefit',
                'managed': False,
            },
        ),
    ]
