# Generated by Django 4.2.7 on 2023-12-24 05:22

import asesmen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_mulai', models.DateField(blank=True, null=True)),
                ('tgl_akhir', models.DateField(blank=True, null=True)),
                ('time_expired', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=asesmen.models.asesmen_image_path)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'asesmen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PivotAsesmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nilai', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pivot_asesmen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubAsesmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(blank=True, max_length=255, null=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_asesmen',
                'managed': False,
            },
        ),
    ]
