# Generated by Django 4.2.7 on 2023-12-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asesmen',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Ide',
        ),
        migrations.DeleteModel(
            name='Jawaban',
        ),
        migrations.DeleteModel(
            name='PivotAsesmen',
        ),
        migrations.DeleteModel(
            name='PivotJawaban',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='SubAsesmen',
        ),
        migrations.DeleteModel(
            name='SubCourse',
        ),
    ]
