# Generated by Django 4.2.7 on 2023-12-24 05:22

from django.db import migrations, models
import materi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=materi.models.user_materi_path)),
                ('bentuk_materi', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=materi.models.materi_image_path)),
                ('artikel', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materi',
                'managed': False,
            },
        ),
    ]
